import Head from "next/head";
import { PRODUCT_QUERY } from "../lib/query";
import { useQuery } from "urql";
import Product from "../components/Product";
import { ProductGalleryContainer, Gallery } from "../styles/Gallery";
import Skeleton from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
import styled from "styled-components";

export default function Tie() {
  //Fetch products from strapi
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  //Checks for the data coming in
  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;
  const products = data.products.data;

  return (
    <div>
      <Head>
        <title>SUITSUPPLY | Modern. Classic.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductGalleryContainer>
        <h1>Tie Collection</h1>
        <Gallery>
          {fetching && <Skeleton />}
          {products
            .filter(product => product.attributes.category == "tie")
            .map((product) => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </Gallery>
      </ProductGalleryContainer>
    </div>
  );
}